server:
  port: 9090

spring:
  application:
    name: HumanVerificationSystem
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:sqlite.db
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HumanVerificationSystemHikariPool
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.SQLiteDialect

logging:
  file:
    path: .\logs
  level:
    root: INFO
  config: classpath:logback-spring.xml

forest:
  max-connections: 20        # 连接池最大连接数
  connect-timeout: 9000        # 连接超时时间，单位为毫秒
  read-timeout: 9000           # 数据读取超时时间，单位为毫秒


redirect:
  url: ${REDIRECT_URL:http://www.baidu.com}